In [2]:
import pandas as pd
import numpy as np
from scipy import stats
from scipy.stats import chi2_contingency

In [3]:
cust_orderflow=pd.read_csv('Costomer+OrderForm.csv')
cust_orderflow

Phillippines   Indonesia       Malta       India
0     Error Free  Error Free   Defective  Error Free
1     Error Free  Error Free  Error Free   Defective
2     Error Free   Defective   Defective  Error Free
3     Error Free  Error Free  Error Free  Error Free
4     Error Free  Error Free   Defective  Error Free
..           ...         ...         ...         ...
295   Error Free  Error Free  Error Free  Error Free
296   Error Free  Error Free  Error Free  Error Free
297   Error Free  Error Free   Defective  Error Free
298   Error Free  Error Free  Error Free  Error Free
299   Error Free   Defective   Defective  Error Free

[300 rows x 4 columns]

In [4]:
cust_orderflow.Phillippines.value_counts()

Error Free    271
Defective      29
Name: Phillippines, dtype: int64

In [5]:
cust_orderflow.Indonesia.value_counts()

Error Free    267
Defective      33
Name: Indonesia, dtype: int64

In [6]:
cust_orderflow.Malta.value_counts()

Error Free    269
Defective      31
Name: Malta, dtype: int64

In [7]:
cust_orderflow.India.value_counts()

Error Free    280
Defective      20
Name: India, dtype: int64

In [8]:
obs=np.array([[271,267,269,280],[29,33,31,20]])
obs                                                           # Make contingency table

array([[271, 267, 269, 280],
       [ 29,  33,  31,  20]])

In [24]:
stats.chi2_contingency(obs)

(3.858960685820355,
 0.2771020991233135,
 3,
 array([[271.75, 271.75, 271.75, 271.75],
        [ 28.25,  28.25,  28.25,  28.25]]))

In [28]:
chi2_score,pval,dof,expectedtable=stats.chi2_contingency(obs)
print('*****************************************************')
print('chi-squared value  : ',round(chi2_score,5))
print('pval               : ',round(pval,5))
print('Degrees of freedom : ',dof)
print('Expected Table     : \n',obs)
print('*******************************************************')

*****************************************************
chi-squared value  :  3.85896
pval               :  0.2771
Degrees of freedom :  3
Expected Table     : 
 [[271 267 269 280]
 [ 29  33  31  20]]
*******************************************************


====================================================================================================
#### Hypothesis Formulation :

##### Ho : Independence of categorical variables (customer order forms defective % does not varies by centre) 
##### Ha : Dependence of categorical variables (customer order forms defective % varies by centre)
====================================================================================================

In [33]:
#level of signifcance -5% ie,At 5% of signifcance,do we reject or not rejet ?

if pval<0.5:
    print('we do not reject Null Hypothesis and we can claim that Independence of categorical variables (customer order forms defective % does not varies by centre')
else:
    print('we reject Null Hypothesis and we can consider Dependence of categorical variables (customer order forms defective % varies by centre')

we do not reject Null Hypothesis and we can claim that Independence of categorical variables (customer order forms defective % does not varies by centre
